export const SimplyFeedMcpEnvs = {
  SIMPLY_FEED_CONFIG_BLOB_NAME: "SIMPLY_FEED_CONFIG_BLOB_NAME",
  SIMPLY_FEED_CONFIG_FILE_NAME: "SIMPLY_FEED_CONFIG_FILE_NAME",
  SIMPLY_FEED_STORAGE_CONNECTION_STRING: "SIMPLY_FEED_STORAGE_CONNECTION_STRING",
  SIMPLY_FEED_STORAGE_FILE_FOLDER: "SIMPLY_FEED_STORAGE_FILE_FOLDER",
  SIMPLY_FEED_LLM_API_KEY: "SIMPLY_FEED_LLM_API_KEY",
  SIMPLY_FEED_LLM_BASE_URL: "SIMPLY_FEED_LLM_BASE_URL",
  SIMPLY_FEED_LLM_MODEL: "SIMPLY_FEED_LLM_MODEL",
  SIMPLY_FEED_ITEMS_RETENTION_DAYS: "SIMPLY_FEED_ITEMS_RETENTION_DAYS",
} as const;
